# YAML Github file to build the .net core 8.0 project
name: dotnet package

on: [push]

jobs:
    build:
  
      runs-on: windows-latest
      strategy:
        matrix:
          dotnet-version: [ '8.0.x' ]
  
      steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Install dependencies
          run: dotnet restore
        - name: Publish
          run: dotnet publish -c Release -p:PublishSingleFile=true
        - name: Archive artifact
          uses: actions/upload-artifact@v4
          with:
              name: publish Windows x64 single executable file
              path: ${{ github.workspace }}\ConsoleApp2\publish\net8.0-windows10.0.22621.0\win-x64\publish